# Site settings
title: Ocean Bioinformatics
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Bioinformatics blog of Erik van den Bergh
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://erikvdbergh.github.io" # the base hostname & protocol for your site
twitter_username: erikvdbergh
github_username:  erikvdbergh

# Build settings
markdown: kramdown
future: true

paginate: 4
excerpt_separator: "<!-- more -->"

author: Erik van den Bergh

gems: [jekyll-paginate]
